### ISSUE TITLE
Channels data ranges and meaning

### ISSUE THREAD

**Issue by adriantabirta** [tii-racing/drone-racing-dataset#3]
Please explain

`10. channels_[roll/pitch/thrust/yaw] | 1 | int ∈[1000,2000]` - what does this thrust means? [1000-2000] why? roll/pitch//yaw isn't like [-Pi-Pi]?

**Comment by MichaelBosello** [comment]
The data in the columns `channels_[roll/pitch/thrust/yaw]` are the Radio Controller's channels (i.e., the stick positions acted by the pilot). **Betaflight (BF) convention uses 1000 as the minimum channel and 2000 as the maximum channel**. The minimum channel for the thrust results in 0.5% thrust as per BF settings, and the maximum channel will result in the maximum thrust of ~40N. For the bodyrates, according to the BF rate profile (you can check the one used in the dataset in [L108-L113 of BTFL_cli_backup.txt](https://github.com/tii-racing/drone-racing-dataset/blob/2abb42af37d43c933804bd9c0dd2503329ee47cf/quadrotor/BTFL_cli_backup.txt#L108-L113)) they go from a minimum of 0 rad/s to a maximum of 8.02 rad/s.

Depending on your application, there may be more suitable data rather than the channels ones. Please refer to the [companion paper](https://ieeexplore.ieee.org/document/10452776) (or the [free pre-pint](https://arxiv.org/pdf/2311.02667)) for more information about the data.
